# Kitty terminal config for local ArchMerOS sysc-greet previews

font_family DejaVu Sans Mono
font_size 13.0

remember_window_size no
initial_window_width 1600
initial_window_height 900
hide_window_decorations yes

foreground #f5f7ff
background #020407
selection_foreground #020407
selection_background #6ef7a8
cursor #6ef7a8
cursor_text_color #020407
cursor_shape block
cursor_blink_interval 0.5

mouse_hide_wait 2.0
repaint_delay 10
input_delay 3
sync_to_monitor yes

map ctrl+shift+enter no_op
map ctrl+shift+t no_op
map ctrl+shift+n no_op
map ctrl+shift+q no_op
map ctrl+q no_op
map ctrl+shift+o no_op
map ctrl+shift+escape no_op
map ctrl+shift+c no_op
map ctrl+shift+v no_op
map ctrl+shift+plus no_op
map ctrl+shift+minus no_op
map ctrl+shift+equal no_op

shell_integration no-cursor
allow_remote_control no
update_check_interval 0
background_opacity 1.0
