preload = /home/zacmero/Pictures/bg/suzy2.png

wallpaper = DP-2,/home/zacmero/Pictures/bg/suzy2.png
wallpaper = HDMI-A-1,/home/zacmero/Pictures/bg/suzy2.png
wallpaper = DP-3,/home/zacmero/Pictures/bg/suzy2.png

splash = false
ipc = on
