general {
    after_sleep_cmd = sh -lc 'hyprctl dispatch dpms on; ~/.config/archmeros/scripts/archmeros-side-dpms.sh on'
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 300
    on-timeout = /home/zacmero/.config/archmeros/scripts/archmeros-screensaver.sh
}

listener {
    timeout = 600
    on-timeout = /home/zacmero/.config/archmeros/scripts/archmeros-dpms-off.sh
    on-resume = sh -lc 'hyprctl dispatch dpms on; ~/.config/archmeros/scripts/archmeros-side-dpms.sh on'
}
