-- ArchMerOS theme values (generated by archmeros-theme.py)
-- This file is overwritten by the theme engine; do not edit by hand.
return {
    active_border   = { colors = { "rgba(58d6ffff)", "rgba(ff7edbff)" }, angle = 45 },
    inactive_border = "rgba(626da7ad)",
    shadow          = "rgba(05070e9e)",
}
