[general]
framerate = 30
autosens = 1
sensitivity = 100
bars = 20
bar_width = 1
bar_spacing = 0
lower_cutoff_freq = 55
higher_cutoff_freq = 14000

[input]
method = pulse
source = auto
channels = 2
mono_option = average

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
channels = mono
bar_delimiter = 59
frame_delimiter = 10
