$archmeros_transparency_preset = work-clean
$archmeros_active_opacity = 0.95
$archmeros_inactive_opacity = 0.88
$archmeros_blur_enabled = true
$archmeros_blur_size = 6
$archmeros_blur_passes = 1
$archmeros_blur_vibrancy = 0.10
$archmeros_thunar_active_opacity = 0.94
$archmeros_thunar_inactive_opacity = 0.88
$archmeros_walker_active_opacity = 0.98
$archmeros_walker_inactive_opacity = 0.95
$archmeros_terminal_active_opacity = 0.95
$archmeros_terminal_inactive_opacity = 0.90
$archmeros_code_active_opacity = 0.96
$archmeros_code_inactive_opacity = 0.92
