name=Xfce
color=#ffffff

ascii_1=
   █████████                      █████      ██████   ██████                       ███████     █████████
  ███░░░░░███                    ░░███      ░░██████ ██████                      ███░░░░░███  ███░░░░░███
 ░███    ░███  ████████   ██████  ░███████   ░███░█████░███   ██████  ████████  ███     ░░███░███    ░░░
 ░███████████ ░░███░░███ ███░░███ ░███░░███  ░███░░███ ░███  ███░░███░░███░░███░███      ░███░░█████████
 ░███░░░░░███  ░███ ░░░ ░███ ░░░  ░███ ░███  ░███ ░░░  ░███ ░███████  ░███ ░░░ ░███      ░███ ░░░░░░░░███
 ░███    ░███  ░███     ░███  ███ ░███ ░███  ░███      ░███ ░███░░░   ░███     ░░███     ███  ███    ░███
 █████   █████ █████    ░░██████  ████ █████ █████     █████░░██████  █████     ░░░███████░  ░░█████████
░░░░░   ░░░░░ ░░░░░      ░░░░░░  ░░░░ ░░░░░ ░░░░░     ░░░░░  ░░░░░░  ░░░░░        ░░░░░░░     ░░░░░░░░░
---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------
--------------------------------------------

ascii_2=
   █████████                      █████      ██████   ██████                       ███████     █████████
  ███░░░░░███                    ░░███      ░░██████ ██████                      ███░░░░░███  ███░░░░░███
 ░███    ░███  ████████   ██████  ░███████   ░███░█████░███   ██████  ████████  ███     ░░███░███    ░░░
 ░███████████ ░░███░░███ ███░░███ ░███░░███  ░███░░███ ░███  ███░░███░░███░░███░███      ░███░░█████████
 ░███░░░░░███  ░███ ░░░ ░███ ░░░  ░███ ░███  ░███ ░░░  ░███ ░███████  ░███ ░░░ ░███      ░███ ░░░░░░░░███
 ░███    ░███  ░███     ░███  ███ ░███ ░███  ░███      ░███ ░███░░░   ░███     ░░███     ███  ███    ░███
 █████   █████ █████    ░░██████  ████ █████ █████     █████░░██████  █████     ░░░███████░  ░░█████████
░░░░░   ░░░░░ ░░░░░      ░░░░░░  ░░░░ ░░░░░ ░░░░░     ░░░░░  ░░░░░░  ░░░░░        ░░░░░░░     ░░░░░░░░░
---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------
--------------------------------------------

roasts=booting fallback desktop path │ preserving thunar and terminal muscle memory │ keeping recovery lanes open │ waiting for operator credentials
