monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Yamaha_Corporation_Steinberg_UR44-01.*"
      }
      {
        node.name = "~alsa_input.usb-Yamaha_Corporation_Steinberg_UR44-01.*"
      }
    ]
    actions = {
      update-props = {
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
        api.alsa.period-num = 4
        api.alsa.headroom = 1024
      }
    }
  }
]
